### ISSUE TITLE
is this compatible with windows 11?

### ISSUE THREAD

**Issue by eskoONE** [X9VoiD/vmulti-bin#5]
im trying to get opentabletdriver running with vmulti to use windowsink so the pressure sensors work with otd but unfortunately i have not been successful in doing so. installing the vmulti drivers through the .bat doesnt result in a restart as its supposed to i think. the devide does however show up in the devices tab.

this is the error im getting:

```[Plugin:Warning]	Plugin 'VMulti, Version=1.0.0.0' can't be loaded and is likely out of date. (HResult: 0x80131602)
Unable to load one or more of the requested types.
Could not load type 'OpenTabletDriver.Plugin.IValidateBinding' from assembly 'OpenTabletDriver.Plugin, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at OpenTabletDriver.Desktop.Reflection.PluginManager.IsLoadable(Assembly asm)
[Plugin:Warning]	Plugin 'WindowsInk, Version=1.0.0.0' can't be loaded and is likely out of date. (HResult: 0x80131602)
Unable to load one or more of the requested types.
Method 'set_Pointer' in type 'VoiDPlugins.OutputMode.WinInkAbsoluteMode' from assembly 'WindowsInk, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'set_Pointer' in type 'VoiDPlugins.OutputMode.WinInkRelativeMode' from assembly 'WindowsInk, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Could not load type 'OpenTabletDriver.Plugin.Platform.Pointer.IVirtualTablet' from assembly 'OpenTabletDriver.Plugin, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'OpenTabletDriver.Plugin.Platform.Pointer.IVirtualTablet' from assembly 'OpenTabletDriver.Plugin, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'OpenTabletDriver.Plugin.IValidateBinding' from assembly 'OpenTabletDriver.Plugin, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at OpenTabletDriver.Desktop.Reflection.PluginManager.IsLoadable(Assembly asm)
[Detect:Info]	Searching for tablets...
[Detect:Info]	Found tablet 'Huion H1060P'
[Huion H1060P:Info]	Output mode: Absolute Mode
[Huion H1060P:Info]	Display area: [1920x1080@<960. 540>:0°],
[Huion H1060P:Info]	Tablet area: [254x158,75@<127. 79,375>:0°],
[Huion H1060P:Info]	Clipping: Enabled
[Huion H1060P:Info]	Ignoring reports outside area: Disabled
[Huion H1060P:Info]	Tip Binding: [Mouse Button Binding: Left]@0%
[Huion H1060P:Info]	Pen Bindings: Key Binding: E, Key Binding: B
[Huion H1060P:Info]	Express Key Bindings: Multi-Key Binding: Control+Z, Multi-Key Binding: Control+Shift+Z, Key Binding: B, Key Binding: E, Key Binding: P, Key Binding: M, Key Binding: K, Key Binding: Backslash, Key Binding: V, Key Binding: D, Key Binding: C, Key Binding: X
[Settings:Info]	Driver is enabled.
[Plugin:Warning]	Plugin 'VMulti, Version=1.0.0.0' can't be loaded and is likely out of date. (HResult: 0x80131602)
Unable to load one or more of the requested types.
Could not load type 'OpenTabletDriver.Plugin.IValidateBinding' from assembly 'OpenTabletDriver.Plugin, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at OpenTabletDriver.Desktop.Reflection.PluginManager.IsLoadable(Assembly asm)
[Plugin:Warning]	Plugin 'WindowsInk, Version=1.0.0.0' can't be loaded and is likely out of date. (HResult: 0x80131602)
Unable to load one or more of the requested types.
Method 'set_Pointer' in type 'VoiDPlugins.OutputMode.WinInkAbsoluteMode' from assembly 'WindowsInk, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'set_Pointer' in type 'VoiDPlugins.OutputMode.WinInkRelativeMode' from assembly 'WindowsInk, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Could not load type 'OpenTabletDriver.Plugin.Platform.Pointer.IVirtualTablet' from assembly 'OpenTabletDriver.Plugin, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'OpenTabletDriver.Plugin.Platform.Pointer.IVirtualTablet' from assembly 'OpenTabletDriver.Plugin, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'OpenTabletDriver.Plugin.IValidateBinding' from assembly 'OpenTabletDriver.Plugin, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at OpenTabletDriver.Desktop.Reflection.PluginManager.IsLoadable(Assembly asm)
[Settings:Info]	Presets have been refreshed. Loaded 0 presets.
```

im using windows 11 so im thinking this isnt compatible with it? i installed the tablet drivers i was able to find but perhaps there is something else interfering with it? i dont know how to look for it in that case.

would appreciate some assistance with this issue.

**Comment by eskoONE** [comment]
this was an error on my end. i got one of the latest winink version like suggested here https://github.com/X9VoiD/VoiDPlugins/issues/25 and that solved my issue. sry for the inconvenience.
